[FIX] double tool context passed to the _run_agentic_loop
Was getting the following error. It was caused by the extension of the
`_run_agentic_loop` function in `ai_website`. It was editing the value of
the `tool_context` param by editing it from the kwargs though
`tool_context` wasn't passed as a named param in the ai_debug module.
Now it's fixed by passing it as a named param.

RPC_ERROR

Odoo Server Error

Occurred on localhost:8069 on 26/Aug/2026 14:59:59

Traceback (most recent call last):
  File "/home/odoo/src/master/enterprise/ai/controllers/thread.py", line 80, in stream_generator
    for item in response_generator:
  File "/home/odoo/src/master/enterprise/ai/models/ai_session.py", line 207, in _continue_conversation
    for item in self._generate_next_response(
  File "/home/odoo/src/extra_addons/custom/ai_debug/models/ai_session.py", line 183, in _generate_next_response
    yield from super()._generate_next_response(message, pending_tool_response=pending_tool_response)
  File "/home/odoo/src/master/enterprise/ai/models/ai_session.py", line 523, in _generate_next_response
    yield from handle_generator_items(self._run_agentic_loop(
  File "/home/odoo/src/master/enterprise/ai/models/ai_session.py", line 494, in handle_generator_items
    for item in generator:
  File "/home/odoo/src/extra_addons/custom/ai_debug/models/ai_session.py", line 271, in _run_agentic_loop
    for item in super()._run_agentic_loop(
  File "/home/odoo/src/master/enterprise/ai_website/models/ai_session.py", line 43, in _run_agentic_loop
    yield from super()._run_agentic_loop(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AiSession._run_agentic_loop() got multiple values for argument 'tools_context'

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPC_ERROR
        at makeErrorFromResponse (http://localhost:8069/web/assets/debug/web.assets_web.js:34317:19)
        at Proxy.aiGetAgentResponse (http://localhost:8069/web/assets/debug/web.assets_web.js:285872:23)
        at async Proxy.post (http://localhost:8069/web/assets/debug/web.assets_web.js:285944:17)